# Generated by Django 2.0.5 on 2018-05-12 09:01

from django.db import migrations, models
import filebrowser.fields
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DynPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(db_index=True, max_length=100, verbose_name='URL')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('language', models.CharField(default='nb', help_text="Example: 'en-gb' or 'nb'. If not provided default is language default.", max_length=6, verbose_name='language')),
                ('description', models.TextField(max_length=200, verbose_name='description')),
                ('keywords', models.CharField(max_length=200, verbose_name='keywords')),
                ('og_image', filebrowser.fields.FileBrowseField(blank=True, max_length=200, verbose_name='open graph image')),
                ('twitter_card', models.TextField(blank=True, max_length=200, verbose_name='twitter card')),
                ('twitter_image', filebrowser.fields.FileBrowseField(blank=True, max_length=200, verbose_name='twitter image')),
                ('content', tinymce.models.HTMLField(verbose_name='content')),
                ('template_name', models.CharField(blank=True, help_text="Example: 'dynpages/contact_page.html'. If this isn't provided, the system will use 'dynpages/default.html'.", max_length=70, verbose_name='template name')),
            ],
            options={
                'verbose_name': 'Dynamic page',
                'verbose_name_plural': 'Dynamic pages',
                'ordering': ('url',),
            },
        ),
    ]
